### ISSUE TITLE
Provide separate Modelers

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-bpmn-js#1]
**`base`**

* [x] diagram-js-minimap
* [x] diagram-js-origin & @bpmn-io/align-to-origin (exclusive, optional)
  * Default: align-to-origin
  * config.disableAdjustOrigin: diagram-js-origin
* [ ] <del>@bpmn-io/add-exporter</del> --> this would require to set exporter metadata any time
* [x] bpmn-js-executable-fix
* [x] bpmn-js-signavio-compat
* [x] bpmn-js-disable-collapsed-subprocess
* [x] bpmn-js-properties-panel
* [x] BPMN properties provider

**`camunda-cloud`**
cf. [`zeebe-io/zeebe-modeler#BpmnModeler`](https://github.com/zeebe-io/zeebe-modeler/blob/develop/client/src/app/tabs/bpmn/modeler/BpmnModeler.js)

Everything from `base` + zeebe related modules
* [x] context-pad
* [x] palette
* [x] modeling
* [x] replace-menu
* [x] rules
* [x] zeebe-bpmn-moddle
* [x] zeebe-properties-provider (implemented, tests are missing)

**`camunda-platform`**
cf. [`camunda/camunda-modeler#BpmnModeler`](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/bpmn/modeler/BpmnModeler.js)

Everything from `base` + camunda related modules
* [x] camunda-bpmn-moddle
* [x] camunda-properties-provider

**What else?**

available in Camunda Modeler as well, do we need them here? --> I'd vote for no
* [ ] <del>complete-direct-editing</del>
* [ ] <del>global-clipboard</del>
* [ ] <del>hand-tool-on-space</del>
* [ ] <del>properties-panel-keyboard-bindings</del>

-----------------

Related to https://github.com/zeebe-io/zeebe-modeler/issues/288

**Comment by pinussilvestrus** [comment]
**Open questions** (03-02-2021)

* Advertise that thing
  * Update README
  * Create how-to
  * Ask for feedback in other teams

* Do we want to keep the [distinction between `diagram-js-origin` & `align-to-origin`](https://github.com/camunda/camunda-bpmn-js/blob/main/lib/base/Modeler.js#L35)? 
* What to do with `bpmn-js-add-exporter`?
* Is `bpmn-js-disable-collapsed-subprocess` engine related or a basic modeling concern we promote?
* What about styles? Cf. #2 
* What about pre-packaged versions? Cf. #3 
* What about Viewers? Cf. #4

**Comment by pinussilvestrus** [comment]
**Chat with Cawemo** (04-02-2021)

* Would be interested in a similar thing for dmn-js, containing the DMN overview as an example
* Modules should be overridable, also things like executable-fix (which is untyped)
* Would be interested in a separate Cawemo bundle, e.g. excluding the Properties panel

**Comment by pinussilvestrus** [comment]
**Chat with Cloud** (04-02-2021)

* perfect!
* Asked whether it would be possible to also include the Properties Panel close handle + basic styles to properly align the Properties Panel

![image](https://user-images.githubusercontent.com/9433996/106895078-14ad0680-66f0-11eb-9289-5bbc4b44b1d8.png)

**Comment by nikku** [comment]
I'm wondering why we excluded this one as we decided what to include in our distributions:

```
* [ ] @bpmn-io/add-exporter --> this would require to set exporter metadata any time
```

In fact, it is best practice to set an exporter (and required meta-data). We could argue that it makes sense for our consumers to provide it.

**Comment by pinussilvestrus** [comment]
I think we decided this because we don't want to [force our users to set the exporter ](https://github.com/bpmn-io/add-exporter/blob/master/add-exporter.js#L12) (throws an error) any time they use a `camunda-bpmn-js` Modeler. The goal was to keep the configuration effort as small as possible.

But I see that this one should be at least available. Maybe we can update [`bpmn-io/add-exporter`](https://github.com/bpmn-io/add-exporter/blob/master/add-exporter.js#L9) to have the `config.exporter` optional? Or we only include this module in the `camunda-bpmn-js` Modelers once the config is defined.

**Comment by nikku** [comment]
> I think we decided this because we don't want to force our users to set the exporter (throws an error) any time they use a camunda-bpmn-js Modeler. The goal was to keep the configuration effort as small as possible.

That is a valid point. Why not force them to do it though? As mentioned, this is best practice that any of our modeling tools should follow. If a diagram is edited in Optimize it should clearly state `Optimize, v412.1` in the exporter field. If it is edited in the cloud console you could argue for a similar thing.

We could set up a naming conventions on our side and document it. With that in place, enforcing the exporter to be set (and best practices to be followed) should not cause our users too much pain.

**Comment by nikku** [comment]
Created https://github.com/camunda/camunda-bpmn-js/issues/32 to track my feedback.

**Comment by pinussilvestrus** [comment]
Thanks for your feedback 👍  I think it makes sense to enforce it (if it's well documented).
