### ISSUE TITLE
Integrate template icons in Cloud Modeler

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-bpmn-js#106]
__What should we do?__

Make the new template icons available in the Cloud Modeler
* [ ] bump `zeebe-bpmn-moddle`
* [ ] bump `bpmn-js-properties-panel`
* [ ] integrate `@bpmn-io/element-templates-icons-renderer`

__Why should we do it?__

Child of https://github.com/bpmn-io/internal-docs/issues/445

**Comment by MaxTru** [comment]
Implicitly done via https://github.com/camunda/camunda-modeler/pull/2891
