### ISSUE TITLE
TS transpiler throws error

### ISSUE THREAD

**Issue by ColRad** [camunda/camunda-bpmn-js#11]
__Describe the Bug__

When being used in a Typescript setup I get an error: 

`Error: ./node_modules/camunda-bpmn-js/lib/camunda-platform/Modeler.js
Module not found: Error: Can't resolve 'camunda-bpmn-moddle/resources/camunda' in '/home/collin/camunda/console/node_modules/camunda-bpmn-js/lib/camunda-platform'
`
This points to `Modeler.js:L7`

TS is having an issue with json imports that ommit the extension. 

When changing L7 to `import camundaModdle from 'camunda-bpmn-moddle/resources/camunda.json';` everything is fine.

__Environment__

- OS: Ubuntu 20.04
- Modeler version: 0.1.0-alpha.0

**Comment by pinussilvestrus** [comment]
Thanks for reporting. 

I'll have a look at whether it could be resolved by basic typescript configuration. If not, we should just update the moddle imports, it should work without major configuration effort.

**Comment by ColRad** [comment]
Cool, thanks for checking!!
I already tried: `"resolveJsonModule": true`but with no success

**Comment by pinussilvestrus** [comment]
We ended up fixing it by updating the imports (cf. https://github.com/camunda/camunda-bpmn-js/pull/12).

Already released under `v0.1.0-alpha.1`. Thanks a lot!
