### ISSUE TITLE
Provider viewers via camunda-bpmn-js

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-bpmn-js#110]
__Is your feature request related to a problem? Please describe.__

At the moment, camunda-bpmn-js only exposes a distribution of the bpmn-js modeler (ie. include moddle, propPanel, ...).

With recent changes (in particular custom icon renderer cf. https://github.com/camunda/camunda-bpmn-js/pull/108), also consumers of a viewer (viewer or navigatedViewer) need to include custom modules to have the desired end-2-end experience.

At the moment, they would need to manually build their bpmn-js viewer consiting of bpmn-js#viewer, moddle, customRendererModule.

__Describe the solution you'd like__

Offer a viewer and navigatedViewer component for camunda bpmn-js which would include the respective moddle, and the custom renderer component (c.f. https://github.com/camunda/camunda-bpmn-js/pull/108). Maybe even more.

__Describe alternatives you've considered__

* Keep as is.
* Make custom icon renderer bpmn-js core concern.

__Additional context__

Raised within https://github.com/camunda/camunda-bpmn-js/pull/108

**Comment by pinussilvestrus** [comment]
Is this a duplicate of: https://github.com/camunda/camunda-bpmn-js/issues/4? Maybe we can merge both issues with the new information we've got.

**Comment by MaxTru** [comment]
Closing as duplicate of #4 indeed :-)
