### ISSUE TITLE
CI on MacOS often times out

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-bpmn-js#111]
__Describe the Bug__

CI on MacOS often times out

__Steps to Reproduce__

Trigger CI run on MacOS.

(Notice this does not always happen)

Example: https://github.com/camunda/camunda-bpmn-js/runs/5846275222?check_suite_focus=true
![Screenshot_20220406_085917](https://user-images.githubusercontent.com/42800119/161914517-64d53687-db97-4e9d-aa25-6d8370102d6d.png)

__Expected Behavior__

CI should not time out

__Environment__

MacOS CI

**Comment by smbea** [comment]
I experience the same

**Comment by pinussilvestrus** [comment]
It could be that we fixed this via https://github.com/camunda/camunda-bpmn-js/pull/116, as we removed the long-running integration tests for the behaviors. 

Let's double-check it, but [the builds](https://github.com/camunda/camunda-bpmn-js/actions) look clean for almost a month now!

**Comment by pinussilvestrus** [comment]
Indeed we removed the flaky test (cf. [this build from the past](https://github.com/camunda/camunda-bpmn-js/runs/5496001003?check_suite_focus=true#step:7:115)). 

```
Chrome Headless 90.0.4427.0 (Mac OS 11.6.4) camunda-cloud/features/modeling - UpdatePropagateAllChildVariablesBehavior (integration tests) remove zeebe:IoMapping when toggling on with outputParameters <propagateAllChildVariables> explicitly set "before each" hook for "should undo/redo" FAILED
	Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

We [moved the integration test to the properties panel](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/test/spec/provider/zeebe/OutputPropagationProps.spec.js#L587), where I believe we are even better on handling UI interactions and waiting for changes properly (e.g., via `waitFor` helpers). 

I also triggered [a couple of builds](https://github.com/camunda/camunda-bpmn-js/runs/6424848774) manually, and it confirms we are good now. Kudos to @philippfromme to make lives for our mac users easier 👏 😄 

Let's close. If we see things are coming back, let's re-open.
