### ISSUE TITLE
[0.13.0] Missing `element-templates.css` file

### ISSUE THREAD

**Issue by boris-petrov** [camunda/camunda-bpmn-js#124]
__Describe the Bug__

Updating to that version causes my project to not build: `Error: Can't resolve './element-templates.css' in '/home/boris/project/node_modules/camunda-bpmn-js/dist/assets'`. And indeed such a file doesn't exist. It is however imported in `camunda-bpmn-js/dist/assets/camunda-cloud-modeler.css` and `camunda-bpmn-js/dist/assets/camunda-platform-modeler.css`. I believe this is a bug.

__Steps to Reproduce__

See above.

__Expected Behavior__

No error.

__Environment__

- OS: Linux
- Modeler version: 0.13.0

**Comment by nikku** [comment]
@philippfromme Did we fall for https://github.com/camunda/camunda-bpmn-js/issues/105 again? :slightly_smiling_face:

**Comment by philippfromme** [comment]
Yes, I've prepared a fix for it: https://github.com/camunda/camunda-bpmn-js/pull/125
