### ISSUE TITLE
Enable all BPMN elements for C8 diagrams

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-bpmn-js#166]
__What should we do?__

* [ ] Enable all diagram elements for C8

__Why should we do it?__

As [decided](https://github.com/bpmn-io/internal-docs/issues/644) we want to allow our users to model all BPMN elements in C8 diagrams and [resort to linting to identify incompatible (for execution) elements](https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/46).

**Comment by marstamm** [comment]
closed with https://github.com/camunda/camunda-bpmn-js/pull/196

**Comment by felix-mueller** [comment]
@CatalinaMoisuc I am really looking forward to see this in Web modeler, do we know when this change will be deployed already? *.*

**Comment by christian-konrad** [comment]
@felix-mueller here's the epic for this, please review: https://github.com/camunda/product-hub/issues/611
