### ISSUE TITLE
any support for typescript (d.ts) declaration files

### ISSUE THREAD

**Issue by soorireddy** [camunda/camunda-bpmn-js#199]
__Is your feature request related to a problem? Please describe.__

when we use import in typescript:

```
Could not find a declaration file for module 'camunda-bpmn-js/lib/camunda-platform/Modeler'. 'd:/sss-ws/camuda-bpmn-test/node_modules/camunda-bpmn-js/lib/camunda-platform/Modeler.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/camunda-bpmn-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'camunda-bpmn-js/lib/camunda-platform/Modeler';`
```

__Describe the solution you'd like__

@types/camunda-bpmn-js or .d.ts files as part of build

__Describe alternatives you've considered__

None.

__Additional context__

None.

**Comment by nikku** [comment]
Tracked upstream via https://github.com/bpmn-io/bpmn-js/issues/1002, https://github.com/bpmn-io/diagram-js/issues/481. Moving to backlog for the moment as this is nothing that is an easy pick for us.

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/camunda-bpmn-js/commit/cae78d247f8f13ab1ee941d7a7a5be4893a1837f. [diagram-js@12](https://www.npmjs.com/package/diagram-js/v/12.0.0) and [bpmn-js@13](https://www.npmjs.com/package/bpmn-js/v/13.0.0) include type declarations.

**Comment by philippfromme** [comment]
@boris-petrov Seems like I was to keen on closing this issue. 🙈

**Comment by nikku** [comment]
We added type definitions with [`v2.2.0`](https://github.com/camunda/camunda-bpmn-js/blob/main/CHANGELOG.md#220).
