### ISSUE TITLE
Add element templates to replace menu

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-bpmn-js#204]
__What should we do?__

Add element templates to replace menu options

__Why should we do it?__

In the context of support replace anything, see https://github.com/bpmn-io/bpmn-js/issues/1627

**Comment by nikku** [comment]
@smbea A little summary of our chat (weekly) on this:

* Elements not appearing if `appliesTo: [ element not in list ]` is expected behavior
* For elements to appear (i.e. `ServiceTask -> UserTask` replacement) you have to `appliesTo: [ bpmn:Task or bpmn:ServiceTask,bpmn:UserTask ]`. `elementType` is the designated utility that allows you to define into which element type the element is changed during replace.

**Comment by nikku** [comment]
@smbea I've commented [on the PR](https://github.com/camunda/camunda-bpmn-js/pull/207). 

The solution looks simple enough; let's make sure it plugs in correctly end-to-end, also including edge cases (service task backed template -> service task (unbind template)).

Also does it make sense to structure this in accordance with bpmn-js feature structure?

**Comment by nikku** [comment]
From discussions with @marstamm when we fixed that issue I remember that we did the least effort thing to build it.

I cannot reproduce https://github.com/camunda/camunda-bpmn-js/issues/204#issuecomment-1332694060 [on the connectors extension](https://bpmn-io.github.io/bpmn-js-connectors-extension/?aa=1), unfortunately.

![capture oLfjPO_optimized](https://user-images.githubusercontent.com/58601/205028249-d8564eb9-d891-4587-b903-9fca4067a556.gif)

**Comment by marstamm** [comment]
[FYI]: this is the commit that changed the unlink entry position: https://github.com/bpmn-io/bpmn-js-connectors-extension/commit/0ec6a11ca5d9d3c680fa5693d53d856d3f64a20a

**Comment by nikku** [comment]
@smbea In this case the implementation shall hook the task up in front of the next element in the line. It may be broken, then we need to fix it.

My suggestion is: Let's incorporate it, build some basic test coverage around it, and investigate + fix all bugs we find in the process.
