### ISSUE TITLE
Element template names are not displayed in replace menu entries

### ISSUE THREAD

**Issue by smbea** [camunda/camunda-bpmn-js#220]
__Describe the Bug__

Element template names are not displayed in replace menu entries.

![Screenshot 2022-12-14 at 11 42 57](https://user-images.githubusercontent.com/25825387/207575154-315cd9d3-18e5-474e-ba1f-7bdaf58ee158.png)

__Steps to Reproduce__

1. disable connectors extension 
2. open replace menu for a service task
3. see that template names are not displayed

__Expected Behavior__

Element template names should be displayed as the entry label

**Comment by nikku** [comment]
I'd remove the connectors extension and/or add an additional test case that tests with the extension.
