### ISSUE TITLE
Remove template properties when replacing template tasks with stock BPMN types

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-bpmn-js#250]
### Is your feature request related to a problem? Please describe.

As a (low code) user I see template/connector tasks as something disconnected from the underlying BPMN task. User reports indicate that switching back from a _inbound webhook start_ to a _blank start event_ or switching between a _REST connector_ and a _service task_ shall not keep the technical connector bindings (after switch/replace it is not a connector task anymore). 

### Describe the solution you'd like

When switching from a connector activity to the plain BPMN pendant using the replace menu remove all connector related extension properties. The current behavior ("unlink") shall still be available through the properties panel in rare circumstances where I need it:

![capture mN2dGy_optimized](https://user-images.githubusercontent.com/58601/222728438-17077531-a3e8-406f-819d-413ac20fe23f.gif)

Go one step further (stage 2) we can consider replacing templated elements with _any_ BPMN element. What shall happen when we replace a REST task (based on `ServiceTask`) with a send task? Again I'd assume that _all_ template defined properties are removed.

### Describe alternatives you've considered

Keep the existing behavior. 

### Additional context

Raised a number of times, internal and external. Cf. also [here](https://camunda.slack.com/archives/CKGH9LR40/p1677835160476449).

**Comment by nikku** [comment]
Let's move it to backlog and await further feedback. This is not immediately actionable.

**Comment by nikku** [comment]
This popped up [again](https://camunda.slack.com/archives/CKGH9LR40/p1684753816379599). Let's consider applying that small change with big impact (less surprises!).

**Comment by smbea** [comment]
So the way the properties panel handles removing the template is by using this utility function [`removeTemplate`](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/provider/element-templates/util/templateUtil.js#L19). Of course we can just duplicate this code (tested and works as expected) but is there a reason for this to not be part of the elementTemplates API? Seems like it would be simpler maintenance

**Comment by nikku** [comment]
@smbea This is what I tried to establish; if there is remaining pieces where we don't rely on the API, lets change that. The properties panel _should not ever_ rely on internal bogus utilities to drive important changes.
