### ISSUE TITLE
Re-export types from sub-packages

### ISSUE THREAD

**Issue by boris-petrov** [camunda/camunda-bpmn-js#284]
__What should we do?__

I do something like that in my code:

```ts
modeler.get<Canvas>('canvas').zoom('fit-viewport');
```

In order to type that correctly, I have to use the `Canvas` type. However, it doesn't come from `camunda-bpmn-js`. It comes from `diagram-js/lib/core/Canvas`. Which means I have to add explicitly `diagram-js` in my `package.json` file which is kind of annoying as I only use it in that single place - to get a type definition from it. I'm using `pnpm` which requires me to do that due to its strict nature.

__Why should we do it?__

Because that's generally a good practice - whenever you use some type from a dependency, re-export it to your own clients so they don't hit cases like this.

**Comment by nikku** [comment]
The workaround (require `diagram-js` explicitly) actually sounds reasonable to me. Also, this happens only if you use a super strict bundler; it does not happen if you use a bundler such as `npm`.

We'll otherwise re-export `diagram-js > bpmn-js > camunda-bpmn-js`, causing loads of duplication.
