### ISSUE TITLE
Subscription Correlation key is not saved

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-bpmn-js#315]
__Describe the Bug__
I can not set a Subscription correlation key on a message intermediate catch event

![Recording 2023-10-19 at 14 19 45](https://github.com/camunda/camunda-bpmn-js/assets/21984219/b323343f-15b7-4d5c-a709-d42095f6342c)

__Steps to Reproduce__

1. Add a message intermediate Catch event
2. add Correlation Key
3. Switch elements back and forth
4. See that it is not comited to the model/XML

__Expected Behavior__

I can set a Correlation key

__Environment__

- OS: [e.g. MacOS 10.2, Windows 10]
- Modeler version: 3.5.0

**Comment by marstamm** [comment]
Not reproduceable with v3.4.0, so 8d8d7ccc65c028067100fd427a28ce1bf54606d6 seems to be the commit that breaks it

**Comment by nikku** [comment]
[Fixed in `v3.6.0`.](https://camunda.slack.com/archives/CKGH9LR40/p1697722486136969?thread_ts=1697717361.863099&cid=CKGH9LR40)
