### ISSUE TITLE
Add market place support to contextual menus

### ISSUE THREAD

**Issue by marcellobarile** [camunda/camunda-bpmn-js#322]
__Is your feature request related to a problem? Please describe.__

With https://github.com/camunda/web-modeler/issues/6066 we have introduced a new icon, to open the marketplace browse dialog, to the following contextual menus:
`bpmn-create`, `bpmn-replace`, `bpmn-append`, and `element-template-chooser`.
We did it by registering an extension provider for each of them: https://github.com/camunda/web-modeler/blob/da75c66b3009763a84f7978d0c624c3f6488cba0/webapp/src/App/Pages/Diagram/BpmnJSExtensions/browseMarketplaceExtension/BrowseMarketplaceExtension.js#L29-L32

We have also added a new call to action when there are no search results, and we did it by listening for mutations on the DOM node: https://github.com/camunda/web-modeler/blob/da75c66b3009763a84f7978d0c624c3f6488cba0/webapp/src/App/Pages/Diagram/BpmnJSExtensions/browseMarketplaceExtension/BrowseMarketplaceExtension.js#L74C3-L91C4

The second approach, looks error-prone and hard to maintain (e.g. what if selectors change in the core libraries?); but at that time it was the only viable solution to achieve the requirement.

__Describe the solution you'd like__

Do we have, or might implement, something better to add the marketplace icon?
Would it be possible to expose something (e.g. a rendering function) to customize or extend the search results?

__Additional context__

PR with changes: https://github.com/camunda/web-modeler/pull/6154/files#

What does it look like:
![image](https://github.com/camunda/camunda-bpmn-js/assets/1809476/8ed15097-95ca-493d-abc0-e6cfa7714701)
![image](https://github.com/camunda/camunda-bpmn-js/assets/1809476/2d4e0b4d-6574-49aa-8497-f2f6eb3a4c94)
![image](https://github.com/camunda/camunda-bpmn-js/assets/1809476/158e1016-3fac-4273-a82b-73deba82ea6a)

----

Depends on https://github.com/bpmn-io/diagram-js/issues/846

**Comment by nikku** [comment]
Moving to `ready` to un-park this item.

**Comment by nikku** [comment]
@marcellobarile Via https://github.com/bpmn-io/diagram-js/pull/847 you'll be able to create a popup menu provider that contributes a custom empty state. This way you shall be able to implement your use-case.

**Comment by marcellobarile** [comment]
great news @nikku ! I'll prepare an issue on our end to embrace the change! :)

**Comment by nikku** [comment]
Will be released with diagram-js@14.0.0
