### ISSUE TITLE
extention user assignee  input=>select

### ISSUE THREAD

**Issue by ruanzy** [camunda/camunda-bpmn-js#380]
extention user assignee  input=>select

----

Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/708

**Comment by ruanzy** [comment]
<img width="248" alt="0894c5cd21c862969e3c9f5a70c4242e" src="https://github.com/user-attachments/assets/04b1c668-71fe-4799-a9c2-c1de62cc0a27">
<img width="190" alt="1727182062803_FE7DBE0D-0F7F-479e-ABA0-B2AD85608D45" src="https://github.com/user-attachments/assets/5f0e3b03-ac13-40b5-8c33-130e0da3ec7b">

**Comment by nikku** [comment]
Where would you like us to populate the list from?

**Comment by ruanzy** [comment]
![image](https://github.com/user-attachments/assets/805313c3-93a8-4016-8d45-573d72744566)

const array = ['tom', 'mike']

**Comment by nikku** [comment]
Thanks for the suggestion. As I understand you want certain fields to be suggested from context. 

We track that issue via https://github.com/bpmn-io/bpmn-js-properties-panel/issues/708.
