### ISSUE TITLE
Provide Viewer and NavigatedViewer for each module

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-bpmn-js#4]
__Is your feature request related to a problem? Please describe.__

Currently, this project only serves the [modeling capabilities](https://github.com/camunda/camunda-bpmn-js/tree/main/lib) of the distributions. However, we should consider users want to render only, e.g. via `Viewer` or `NavigatedViewer`.

With recent changes (in particular custom icon renderer cf. https://github.com/camunda/camunda-bpmn-js/pull/108), this might be in particular important and relevant. Otherwise consumers of a viewer (viewer or navigatedViewer) need to include custom modules to have the desired end-2-end experience.

__Describe the solution you'd like__

Provide

* `base`
  * [ ] `Viewer`
  * [ ] `NavigatedViewer`
* `camunda-cloud`
  * [ ] `Viewer`
  * [ ] `NavigatedViewer`
* `camunda-platform`
  * [ ] `Viewer`
  * [ ] `NavigatedViewer`

__Describe alternatives you've considered__

/

__Additional context__

/

**Comment by MaxTru** [comment]
Let's also inform other teams of the change once we have it

**Comment by marstamm** [comment]
Seeing that most of the modules are modeling modules and from the use case of the modeler in embedded applications without a minimap, I see the following modules:

- base viewer
  - default viewers from bpmn-js
- cloud viewer
  - disable drilldown
  - iconRenderer
  - zeebeModdle
- platform viewer
  - camundaModdle

The moddle extension is not necessary as of now, but always good to have it anyway. We will also provide bundled CSS for the viewers so it is not necessary to include multiple CSS files (diagram-js.css + bpmn-js.css)
