### ISSUE TITLE
None Intermediate Throw Event should not have output mapping

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-bpmn-js#52]
__Describe the Bug__

Currently, it's possible to set output mapping in an Intermediate Throw Event. According to [the docs](https://docs.camunda.io/docs/product-manuals/concepts/variables#output-mappings), it should not be possible:

> Output mappings can be used to customize how job/message variables are merged into the process instance. They can be defined on service tasks, receive tasks, message catch events, and subprocesses.

__Steps to Reproduce__

1. Create an Intermediate Throw Event in Camunda Modeler 4.10.0
2. Open the properties panel
3. now this happens

__Expected Behavior__

It should not be allowed.

__Environment__

- OS: any
- Modeler version: 4.10.0

@menski Can you please clarify which shapes can have output mappings? Especially if it should be allowed for more element types than those mentioned currently in the docs (e.g. Business Rule Task?).

**Comment by menski** [comment]
@saig0 can you answer @barmac question to me

> Can you please clarify which shapes can have output mappings? Especially if it should be allowed for more element types than those mentioned currently in the docs (e.g. Business Rule Task?).

**Comment by saig0** [comment]
@barmac output variable mappings **should** be possible for none intermediate throw events. The [implementation](https://github.com/camunda-cloud/zeebe/issues/7765) for Camunda Cloud version `1.2.0` will support output mappings.

Please have a look at the upcoming docs: https://stage.docs.camunda.io/docs/reference/bpmn-processes/none-events/none-events/#variable-mappings

The [other page](https://docs.camunda.io/docs/product-manuals/concepts/variables#output-mappings) doesn't contain an exhausted list of all elements that support output mappings.

In version `1.2.0`, the following elements support output mappings: 
* embedded subprocess
* call activity
* service task
* user task
* receive task
* send task
* business rule task
* script task
* manual task
* multi-instance activity
* (none/message/timer/error) start event (process, subprocess and event subprocess) 
* (message/time) catch event
* (message/timer/error) boundary event
* (none/message) intermediate throw event
* message end event (but not none or error)

**Comment by barmac** [comment]
Amazing, thank you! This means we don't need to change anything regarding none throw event.
