### ISSUE TITLE
Include additional Properties Panel styles and close handle

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-bpmn-js#6]
__Is your feature request related to a problem? Please describe.__

Given #2, we only include the basic properties styles given by `bpmn-js-properties-panel`. To offer the _exact_ same experience as the Camunda Modeler, there are some things missing, for example.

* Properly align Modeler and Properties Container, e.g. [the styles we currently use inside our tests](https://github.com/camunda/camunda-bpmn-js/blob/main/test/camunda-platform/ModelerSpec.js#L20)
* Add a close handle
* Resizing the panel
* ...

![image](https://user-images.githubusercontent.com/9433996/106895500-969d2f80-66f0-11eb-805e-e2c9a2492df8.png)

__Describe the solution you'd like__

__Describe alternatives you've considered__

Don't do it as this is custom behavior.

**Comment by nikku** [comment]
Closing as outdated.
