### ISSUE TITLE
When bumping to bpmn-js@v9.x.x, disable collapsed subprocess editing for cloud diagrams

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-bpmn-js#64]
__Is your feature request related to a problem? Please describe.__

With bpmn-js@9.x.x one will be able to edit contents inside collapsed subprocesses and then collapse them.
This collapsing will initially not be supported by the cloud stack (operate, zeebe). Reason is, that they have other priorities at the moment. They will ensure this works later.

Therefore we have to ensure that no BPMN diagrams with collapsed subprocesses with contents can be created for Cloud (not via the Camunda Modeler and also not via the Web IDE).

__Describe the solution you'd like__

When bumping to bpmn-js@v9.x.x, disable collapsed subprocess editing for cloud diagrams.

Note that will be re-enabled in the future (as soon as cloud gives us the go) 

__Describe alternatives you've considered__

Directly disable in Camunda Modeler and WebIDE.

__Additional context__

https://github.com/bpmn-io/internal-docs/issues/340

**Comment by pinussilvestrus** [comment]
Isn't that already given via [`bpmn-js-disable-collapsed-subprocess`](https://github.com/camunda/camunda-bpmn-js/blob/main/lib/base/Modeler.js#L14)?

**Comment by marstamm** [comment]
closed with [bc74cd2](https://github.com/camunda/camunda-bpmn-js/commit/bc74cd2800fe2b5c0cb874b482392315d9cd8a5c)
