### ISSUE TITLE
Provide Cawemo distribution

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-bpmn-js#7]
__Is your feature request related to a problem? Please describe.__

[Cawemo](https://cawemo.com/) is one possible consumer of a custom Modeler application. Currently, we offer distros for

* camunda-platform
* camunda-cloud

Cawemo has some custom behaviors that differ from the already existing offerings. This includes, as an example, that they don't use the Properties Panel at all, which we serve per default.

__Describe the solution you'd like__

Create custom Cawemo Modeler offering.

_tbd_ what to include and not to include...

__Describe alternatives you've considered__

Add a bundle without the properties panel.

__Additional context__

/

**Comment by nikku** [comment]
Let's close this. No further investments into modeling only, outside of core bpmn.io.
