### ISSUE TITLE
Publish (npm or branch/tag) a version with Zeebe 1.3 features and the new properties panel

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-bpmn-js#71]
__What should we do?__

Publish a version of camunda-bpmn-js with Zeebe 1.3 features and the new properties panel. This could be done via npm or a branch (like we have done so far).

__Why should we do it?__

To enable other teams (@CatalinaMoisuc and @ultraschuppi) to use the new properties panel with Zeebe 1.3 features.

**Comment by MaxTru** [comment]
Closed via https://github.com/camunda/camunda-bpmn-js/pull/76
