### ISSUE TITLE
Only React to `Modeling#updateProperties` and `Modeling#updateModdleProperties` in Behaviors

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-bpmn-js#77]
* [x] only react to `Modeling#updateProperties` and `Modeling#updateModdleProperties` in behaviors

---

Depends on https://github.com/bpmn-io/bpmn-js-properties-panel/issues/535
Child of https://github.com/bpmn-io/internal-docs/issues/358

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-bpmn-js/pull/91
